namespace SpriteKind {
    export const Geschoss = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Laser = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Geschoss)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    Held.vy = -100
    pause(1000)
})
sprites.onOverlap(SpriteKind.Geschoss, SpriteKind.Enemy, function (sprite, otherSprite) {
    Münze = sprites.create(assets.image`Münze`, SpriteKind.Projectile)
})
let Münze: Sprite = null
let Laser: Sprite = null
let Held: Sprite = null
Held = sprites.create(img`
    ................................
    ............dddd................
    ...........dddddd...............
    ...........dfddfd...............
    ...........dddddd...............
    ...........dddddd...............
    ............dddd................
    ...........811618...............
    ...........811618...............
    ...........881688...............
    ...........881688.fff...........
    ..........d881688df.............
    ...........888888...............
    ...........888888...............
    ...........888888...............
    ..........88888888..............
    ..........88888888..............
    ..........888..888..............
    ..........88....88..............
    ..........88....88..............
    ..........88....88..............
    ..........88....88..............
    ..........88....88..............
    ..........88....88..............
    ..........f.....f...............
    ..........ff....ff..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
scene.cameraFollowSprite(Held)
controller.moveSprite(Held, 100, 0)
Held.y = 100
info.setLife(3)
Held.setBounceOnWall(true)
tiles.setCurrentTilemap(tilemap`Level8`)
game.onUpdate(function () {
    if (Held.vx < 0) {
    	
    }
    if (Held.vx > 0) {
    	
    }
})
forever(function () {
    if (Held.overlapsWith(Münze)) {
        info.changeScoreBy(1)
    }
})
